################################################################################
#                                                                              #
#   Copyright 2023 Finebits (https://finebits.com)                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

name: Build and Test

on:
  push:
    branches:
      - main
      - develop
      - release/**
  pull_request:
    branches:
      - main
      - develop
      - release/**

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      project: source/Network.RestClient.sln
      test-project: source/Network.RestClient.sln
      test-report-root: ./source/TestResults
      configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Build the project
      run: dotnet build ${{ env.project }} --configuration ${{ env.configuration }}
        
    - name: Test the project
      run: dotnet test ${{ env.test-project }} --configuration ${{ env.configuration }} --collect:"XPlat Code Coverage" --results-directory="${{ env.test-report-root }}"

    - name: Generate test coverage badge
      if: ${{ env.gist-id != '' && env.gist-auth-token != '' }}
      uses: finebits/github-actions/badges/coverlet-coverage-badge@v1.1.1
      with:
        label-color: "343b42"
        report-root: "${{ env.test-report-root }}/**/"
        report-filename: coverage.cobertura.xml
        gist-filename-format: "${{ github.event.repository.name }}-{0}-test-coverage.json"
        gist-id: ${{ env.gist-id }}
        gist-auth-token: ${{ env.gist-auth-token }}
      env:
        gist-id: ${{ vars.BADGE_COVERLET_COVERAGE_GIST_ID }}
        gist-auth-token: ${{ secrets.TOKEN_GITHUB_GIST }}
